Update github action

diff --git a/.github/workflows/code-scan.yml b/.github/workflows/code-scan.yml
--- a/.github/workflows/code-scan.yml
+++ b/.github/workflows/code-scan.yml
@@ -61,7 +61,8 @@ jobs:
       continue-on-error: true  # Skip error if already configured
 
     - name: Run Psalm analysis
-      run: vendor/bin/psalm --alter --issues=MissingReturnType,UnusedVariable,MissingOverrideAttribute,ClassMustBeFinal,PossiblyUnusedMethod --dry-run --output-format=github > psalm.sarif || true
+      # run: vendor/bin/psalm --alter --issues=MissingReturnType,UnusedVariable,MissingOverrideAttribute,ClassMustBeFinal,PossiblyUnusedMethod --dry-run --output-format=github > psalm.sarif || true
+      run: vendor/bin/psalm --output-format=github > psalm.sarif || echo "Psalm failed, continuing anyway"
 
     - name: Upload SARIF report
       uses: github/codeql-action/upload-sarif@v3
